### ISSUE TITLE
Wordpress procedures

### ISSUE THREAD

**Issue by WebDevJL** [WebDevJL/vps-manager#11]
- [x] MySQL database and user setup: #13 

- [x] Installation: #12 

- [x] Create a Akismet account: https://akismet.com/wordpress/ (to enable SPAM control) and configure the plugin

- [x] ~~FTP Server (*required to install/update plugins*): #15~~Not applicable with `define('FS_METHOD', 'direct');` in wp-config.php

- [x] Security patches : #20

- [x] Performance patches: #14 

- [ ] Backup strategy : #21

- [ ] Staging site feature : #22

- [ ] Theme selection
